### PR TITLE
Automatic removal of unsupported GPU signals and controls

### LINKED ISSUE #2386: GPU signals are exposed even if they are not supported
**Describe the bug**
I tried to read a signal exposed by a GPU IO Group and I expected it to work instead I received a underlying library error.

**GEOPM version**
1.1.0+dev2160gbf0e92f8

**Expected behavior**
geopmread & geopmwrite should only list signals available to the user

**Actual behavior**
geopmread & geopmwrite for GPU IO Groups will list all possible signals, including those that are not available to a given user.

**Error messages produced**
None, by inspection

**Additional context**
The MSRIOGroup now provides a similar feature for pruning signals that are not valid/available (around the HWP vs legacy P-state switch)

### PR DESCRIPTION
**Pull request by lhlawson**
- Relates to #2386 bug report from github issues
- Fixes #2386 change request from github issues.

This PR checks for LevelZero signal and control availability at boot time and removes them from the available list if they cannot be accessed.

Live tested on a system with basic level zero support, unit tests for checking removal of signals also added.

### CODE REVIEW

File: service/src/LevelZeroIOGroup.cpp [hunk 1]
```diff
@@ -484,6 +499,49 @@ namespace geopm
...
+
+                        if(std::isnan(init_setting)) {
+                            // Specialized handling for signals that may be NAN
+                            if(sv.first == "GPU_CORE_FREQUENCY_CONTROL" ||
+                               sv.first == M_NAME_PREFIX + "GPU_CORE_FREQUENCY_CONTROL") {
+
+                                init_setting = read_signal(M_NAME_PREFIX + "GPU_CORE_FREQUENCY_MAX_AVAIL",
+                                                           control_domain_type(sv.first), domain_idx);
+                            }
+                        } else {
```
Comment (bgeltz) [inline service/src/LevelZeroIOGroup.cpp]:
```suggestion
                        } 
                        else {
```

**Review by bgeltz — CHANGES_REQUESTED** [review]

**Review by bgeltz — DISMISSED** [review]

File: service/src/LevelZeroIOGroup.cpp [hunk 2]
```diff
@@ -484,6 +499,50 @@ namespace geopm
...
+                               sv.first == M_NAME_PREFIX + "GPU_CORE_FREQUENCY_CONTROL") {
+
+                                init_setting = read_signal(M_NAME_PREFIX + "GPU_CORE_FREQUENCY_MAX_AVAIL",
+                                                           control_domain_type(sv.first), domain_idx);
+                            }
+                        }
+                        else {
+                            //Try to write the signals
+                            write_control(sv.first, control_domain_type(sv.first), domain_idx, init_setting);
+                        }
```
Comment (lhlawson) [inline service/src/LevelZeroIOGroup.cpp]:
```suggestion

                            //Try to write the signals
                            write_control(sv.first, control_domain_type(sv.first), domain_idx, init_setting);

```

File: service/src/NVMLIOGroup.cpp [hunk 3]
```diff
@@ -236,26 +275,58 @@ namespace geopm
...
+                         ++domain_idx) {
+                        init_setting = read_signal(sv.first, control_domain_type(sv.first), domain_idx);
+
+                        if(std::isnan(init_setting)) {
+                            // Specialized handling for signals that may be NAN
+                            if (sv.first == M_NAME_PREFIX + "GPU_CORE_FREQUENCY_RESET_CONTROL") {
+                                init_setting = 0;
+                            }
+                        }
+                        else if (init_setting == 0 &&
```
Comment (lhlawson) [inline service/src/NVMLIOGroup.cpp]: It's unclear to me why the default GPU_CORE_FREQUENCY_CONTROL value is 0 instead of NAN (defined in initializer list), but either way this is handled as a special case by using the max frequency for the write/read check then calling restore_control.

**Review by cmcantalupo — APPROVED** [review]
