### PR TITLE
GPU Signal & Control cleanup to match documentation

### LINKED ISSUE #2360: LEVELZERO & NVML GPU_ENERGY & GPU_POWER_LIMIT do not use the same aggregation
**Describe the bug**
I expected LEVELZERO::GPU_ENERGY and NVML::GPU_ENERGY_CONSUMPTION_TOTAL (as well as the corresponding high level aliases) to match aggregation types.  Instead one is average and the other is sum.  

Similar issues exist for the power limits.  

**GEOPM version**
By inspection.  geopm v1.1.0+

**Expected behavior**
GPU signals should share aggregation types across implementations for anything exposed or planned to be exposed as a high level alias.

**Actual behavior**
At least two signals (GPU_ENERGY, GPU_POWER_LIMIT) have differing aggregation types.

**Error messages produced**
None.  By inspection

**Additional context**
Found as part of documenting GPU IO Groups.

### PR DESCRIPTION
**Pull request by lhlawson**
Signed-off-by: Lowren Lawson <lowren.h.lawson@intel.com>

- Relates to #2314 feature request from github issues
- Fixes #2360 bug from github issues.

This PR is intended to align the names used in our GPU documentation with those used in the IOGroups themselves, as well as address any issues around aggregation differences, domain differences, etc.

For a list of associated tasks see https://github.com/geopm/geopm/pull/2329#issuecomment-1136335207

### CODE REVIEW

File: service/src/LevelZeroIOGroup.cpp [hunk 1]
```diff
@@ -276,9 +277,10 @@ namespace geopm
                                   },
                                   1 / 1e6
                                   }},
-                              {M_NAME_PREFIX + "GPUCHIP_ACTIVE_TIME_TIMESTAMP", {
-                                  "Compute/GPU chip active time reading timestamp"
-                                  "\nValue cached on LEVELZERO::GPUCHIP_ACTIVE_TIME read",
+                              {M_NAME_PREFIX + "GPU_ACTIVE_TIME_TIMESTAMP", {
+                                  "The timestamp for the LEVELZERO::GPU_ACTIVE_TIME read in seconds."
```
Comment (cmcantalupo) [inline service/src/LevelZeroIOGroup.cpp:281]:
```suggestion
                                  "The timestamp when the LEVELZERO::GPU_ACTIVE_TIME signal was last read measured in seconds."
```

**Review by cmcantalupo — APPROVED** [review]
