### PR TITLE
Make `POSIXSignalTest.siq_queue_EPERM` consider elevated permissions

### LINKED ISSUE #2382: POSIXSignalTest.sig_queue_EPERM test failing
**Describe the bug**
I tried to run the tests of geopmd and I expected them to pass instead one failed

**GEOPM version**
2.0.0+rc1

**Expected behavior**
All tests passing

**Actual behavior**
1 test is failing

**Error messages produced**
FAIL: test/gtest_links/POSIXSignalTest.sig_queue_EPERM
Was debug messaging was enabled at build time? No

**Additional context**

see https://bugs.gentoo.org/852260
log https://852260.bugs.gentoo.org/attachment.cgi?id=785567

### PR DESCRIPTION
**Pull request by Krebrov001**
Add a function `has_elevated_permissions()` to check if the current user
has elevated permissions by examining the `CapEff` field in the status
file of the running process's proc entry.

Signed-off-by: Konstantin Rebrov <konstantin.rebrov@intel.com>

- Relates to #2382

### CODE REVIEW

File: service/test/POSIXSignalTest.cpp [hunk 1]
```diff
@@ -61,6 +69,40 @@ void POSIXSignalTest::TearDown(void)
     sigprocmask(SIG_SETMASK, &m_backup_sigset, nullptr);
 }
 
+bool POSIXSignalTest::has_elevated_permissions(void) const
+{
+    uint64_t cap = 0;
+    uint64_t cap_sys_admin = 0x00200000;  // TODO: magic number, is there a #define for it?
```
Comment (Krebrov001) [inline service/test/POSIXSignalTest.cpp:75]: magic number, is there a `#define` for it?

File: service/test/POSIXSignalTest.cpp [hunk 2]
```diff
@@ -201,10 +243,13 @@ TEST_F(POSIXSignalTest, sig_queue_ESRCH)
  */
 TEST_F(POSIXSignalTest, sig_queue_EPERM)
 {
-    if (geteuid() == 0) {
+    if (geteuid() == 0) {  // the root user
         std::cerr << "Warning: <geopm> Skipping POSIXSignalTest.sig_queue_EPERM cannot be run by user \"root\"\n";
     }
-    else {
+    else if (has_elevated_permissions()) {  // the non root user with elevated permissions
+        m_posix_sig->sig_queue(1, SIGCONT, 2);  // TODO: how to do EXPECT_NO_THROW?
```
Comment (Krebrov001) [inline service/test/POSIXSignalTest.cpp]: How to do `EXPECT_NO_THROW`? Like for any other non root user, we used a `GEOPM_EXPECT_THROW_MESSAGE` to say that we are expecting `sig_queue()` to necessarily fail. So if it doesn't throw an exception, the test would fail.

For the non root user with elevated permissions, can we have a similar assertion that excepts the call `sig_queue()` to necessarily **not** fail, or necessarily **not** throw an exception. So if it throws an exception, the test would fail, and if it doesn't throw, the test would pass. How can we do that?

**Review by Krebrov001 — COMMENTED** [review]
Please answer my questions.

File: service/test/POSIXSignalTest.cpp (hunk 2 above)
Comment (cmcantalupo) [reply service/test/POSIXSignalTest.cpp]: If the test throws an unhandled exception, gtest considers it a failure, that is why there isn't an "EXPECT_NO_THROW" macro.  Everything is expected not to throw :)

File: service/test/POSIXSignalTest.cpp (hunk 1 above)
Comment (cmcantalupo) [inline service/test/POSIXSignalTest.cpp]: We probably just want to check for CAP_KILL which is 0x20, but perhaps renaming the function as well "has_cap_kill()"

File: service/test/POSIXSignalTest.cpp (hunk 2 above)
Comment (Krebrov001) [reply service/test/POSIXSignalTest.cpp]: > If the test throws an unhandled exception, gtest considers it a failure, that is why there isn't an "EXPECT_NO_THROW" macro. Everything is expected not to throw :)

So nothing else needs to be done here?

File: service/test/POSIXSignalTest.cpp [hunk 3]
```diff
@@ -61,6 +69,40 @@ void POSIXSignalTest::TearDown(void)
...
+bool POSIXSignalTest::has_elevated_permissions(void) const
+{
+    uint64_t cap = 0;
+    uint64_t cap_sys_admin = 0x00200000;  // TODO: magic number, is there a #define for it?
+    pid_t pid = getpid();
+
+    std::string status_path = "/proc/" + std::to_string(pid) + "/status";
+
+    // TODO: This is a very memory inefficient algorithm and should be replaced some day.
+    try {
```
Comment (cmcantalupo) [inline service/test/POSIXSignalTest.cpp]: Why the catch all?  Under what conditions would we expect this function to throw?

**Review by cmcantalupo — CHANGES_REQUESTED** [review]
Looks pretty good.  Just a couple of comments.

**Review by cmcantalupo — APPROVED** [review]
LGTM
