### PR TITLE
Fix energy accounting for application totals in report

### LINKED ISSUE #1093: Energy totals in report incorrect
```
Application Totals:
    runtime (sec): 10.0534
    package-energy (joules): 1235.31
    dram-energy (joules): -65427.2
    power (watts): 122.874
    network-time (sec): 0
    ignore-time (sec): 0
    geopmctl memory HWM: 39324 kB
    geopmctl network BW (B/sec): 0
```

The ApplicationIO class uses read_signal() not sample() to calculate the energy values.  The new implementation doesn't borrow roll-over data from the read_batch() calls to service the read_signal() calls.  This make sense, but the ApplicationIO must be changed to use sample for these caluclations.

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Fixes #1093 from github issues
- The ApplicationIO class must use the PlatformIO sample()
  API not read_signal() in order to properly deal with rollover
  of the energy counters issues in energy counters.

### CODE REVIEW

File: src/ApplicationIO.cpp [hunk 1]
```diff
@@ -101,8 +104,10 @@ namespace geopm
             }
             m_is_connected = true;
 
-            m_start_energy_pkg = current_energy_pkg();
-            m_start_energy_dram = current_energy_dram();
+            m_energy_pkg_idx = m_platform_io.push_signal("ENERGY_PACKAGE", GEOPM_DOMAIN_BOARD, 0);
+            m_energy_dram_idx = m_platform_io.push_signal("ENERGY_DRAM", GEOPM_DOMAIN_BOARD, 0);
+            m_start_energy_pkg = m_platform_io.sample(m_energy_pkg_idx);
```
Comment (cmcantalupo) [inline src/ApplicationIO.cpp]: This is a non-starter.  We cannot sample at this point in the stack.  We will not be able to push any signals other than the ProfileIO signals.  The right solution is to push_signal() and call read_signal() here.  The call at the end should be to sample().

File: src/Reporter.cpp [hunk 2]
```diff
@@ -288,13 +303,14 @@ namespace geopm
         // extra runtimes for epoch region
         report << "    epoch-runtime-ignore (sec): " << application_io.total_epoch_runtime_ignore() << std::endl;
 
-        double total_runtime = application_io.total_app_runtime();
-        double app_energy_pkg = application_io.total_app_energy_pkg();
+        double total_runtime = m_platform_io.sample(m_app_time_signal_idx);
```
Comment (dianarg) [inline src/Reporter.cpp]: assumes start time is 0

File: test/ApplicationIOTest.cpp [hunk 3]
```diff
@@ -77,6 +79,9 @@ void ApplicationIOTest::SetUp()
     m_epoch_regulator = new MockEpochRuntimeRegulator;
     auto tmp_reg = std::unique_ptr<MockEpochRuntimeRegulator>(m_epoch_regulator);
 
+    m_energy_pkg_idx = 18;
```
Comment (dianarg) [inline test/ApplicationIOTest.cpp]: leftovers here and on 69-70

File: test/ReporterTest.cpp [hunk 4]
```diff
@@ -203,13 +209,19 @@ TEST_F(ReporterTest, generate)
...
-    EXPECT_CALL(m_application_io, total_app_runtime()).WillOnce(Return(56));
-    EXPECT_CALL(m_application_io, total_app_energy_pkg()).WillOnce(Return(2222));
-    EXPECT_CALL(m_application_io, total_app_energy_dram()).WillOnce(Return(2222));
     EXPECT_CALL(m_application_io, total_app_runtime_mpi()).WillOnce(Return(45));
     EXPECT_CALL(m_application_io, total_app_runtime_ignore()).WillOnce(Return(0.7));
     EXPECT_CALL(m_application_io, total_epoch_runtime_ignore()).WillRepeatedly(Return(0.7));
     EXPECT_CALL(m_application_io, total_epoch_runtime()).WillOnce(Return(70.0));
+    EXPECT_CALL(m_platform_io, sample(M_TIME_IDX))
+        .WillOnce(Return(56));
+    EXPECT_CALL(*m_agg, read_batch);
```
Comment (dianarg) [inline test/ReporterTest.cpp:216]: move up above sample

**Review by bgeltz — APPROVED** [review]
