### PR TITLE
Bug fixes for LevelZero initialization, overlapping ranks, and geopmd shutdown

### LINKED ISSUE #2801: Error messages not propagating when ranks are not affinitized to distinct cores
**Describe the bug**
I tried to use geopmlaunch to run an app with ranks that are affinitized to the same cores and I expected an error message to indicate that this is an invalid configuration instead no meaningful error message was produced.

**GEOPM version**
5e829c4c2

**Expected behavior**
```
$ OMP_PROC_BIND=true GEOPM_CTL=process GEOPM_PROFILE= GEOPM_REPORT=geopm.report KMP_AFFINITY=disabled MV2_ENABLE_AFFINITY=0 KMP_WARNINGS=FALSE srun -N 1 -n 3 --cpu-bind v,mask_cpu:0x2,0xF,0xF --export=LD_PRELOAD=libgeopm.so,ALL -- ./print_affinity
srun: Loaded msrsave restore plugin.
cpu-bind=MASK - mcfly1, task  1  1 [83158]: mask 0xf set
cpu-bind=MASK - mcfly1, task  0  0 [83157]: mask 0x2 set
cpu-bind=MASK - mcfly1, task  2  2 [83159]: mask 0xf set
Warning: <geopm> Controller handshake failed at step cpu_affinity, running without geopm.
<geopm> MPI ranks are not affinitized to distinct CPUs
Rank: 0 cgroup CPUs: [0,1,2,3] omp CPUs: [2,3,3,2,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,3,3,3,3,3,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3]
Error: <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=1 : is_writer=1 : Timed out waiting for status 2: at src/ControlMessage.cpp:81
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: PlatformIOImp::restore_control(): Called prior to save_control(): at src/PlatformIO.cpp:872
srun: error: mcfly1: task 0: Aborted (core dumped)
```

**Actual behavior**
```
$ OMP_PROC_BIND=true GEOPM_CTL=process GEOPM_PROFILE= GEOPM_REPORT=geopm.report KMP_AFFINITY=disabled MV2_ENABLE_AFFINITY=0 KMP_WARNINGS=FALSE srun -N 1 -n 3 --cpu-bind v,mask_cpu:0x2,0xF,0xF --export=LD_PRELOAD=libgeopm.so,ALL -- ./print_affinity
srun: Loaded msrsave restore plugin.
cpu-bind=MASK - mcfly1, task  0  0 [82928]: mask 0x2 set
cpu-bind=MASK - mcfly1, task  1  1 [82929]: mask 0xf set
cpu-bind=MASK - mcfly1, task  2  2 [82930]: mask 0xf set
Rank: 0 cgroup CPUs: [0,1,2,3] omp CPUs: [2,2,2,2,2,2,2,2,2,2,2,3,2,2,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,2,0]
Error: <geopm> Runtime error: ControlMessageImp::wait(): mcfly1 : is_ctl=1 : is_writer=1 : Timed out waiting for status 2: at src/ControlMessage.cpp:81
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: PlatformIOImp::restore_control(): Called prior to save_control(): at src/PlatformIO.cpp:872
srun: error: mcfly1: task 0: Aborted (core dumped)
```

In case it's not apparent, the delta between the 2 behaviors are these lines that should be emitted:
```
Warning: <geopm> Controller handshake failed at step cpu_affinity, running without geopm.
<geopm> MPI ranks are not affinitized to distinct CPUs
```

These messages inform the user that their pinning is not valid for use with GEOPM.  Otherwise, the only other way to reach this conclusion is to pull apart the handshake with GDB to understand why there's a ControlMessage timeout.

### LINKED ISSUE #2803: geopmd hanging on shutdown
**Describe the bug**
I tried to shut the service down with systemctl and I expected it to shutdown gracefully instead it hangs, and will eventually be killed with SIGKILL.

**GEOPM version**
5e829c4c2

**Expected behavior**
```
$ sudo systemctl stop geopm
$ journalctl -u geopm
...
Jan 12 16:52:42 mcfly1 systemd[1]: Started Global Extensible Open Power Manager Service.
Jan 12 16:52:43 mcfly1 systemd[1]: Stopping Global Extensible Open Power Manager Service...
Jan 12 16:52:43 mcfly1 systemd[1]: Stopped Global Extensible Open Power Manager Service.
```

**Actual behavior**
```
Jan 12 16:43:07 mcfly1 systemd[1]: Starting Global Extensible Open Power Manager Service...
Jan 12 16:43:08 mcfly1 systemd[1]: Started Global Extensible Open Power Manager Service.
Jan 12 16:43:19 mcfly1 systemd[1]: Stopping Global Extensible Open Power Manager Service...
Jan 12 16:44:50 mcfly1 systemd[1]: geopm.service: State 'stop-sigterm' timed out. Killing.
Jan 12 16:44:50 mcfly1 systemd[1]: geopm.service: Killing process 5581 (geopmd) with signal SIGKILL.
Jan 12 16:44:50 mcfly1 systemd[1]: geopm.service: Main process exited, code=killed, status=9/KILL
Jan 12 16:44:50 mcfly1 systemd[1]: Stopped Global Extensible Open Power Manager Service.
Jan 12 16:44:50 mcfly1 systemd[1]: geopm.service: Unit entered failed state.
Jan 12 16:44:50 mcfly1 systemd[1]: geopm.service: Failed with result 'timeout'.
```

**Additional context**
This only started happening since 09c039976 was merged recently.  It looks like I missed handling the event loop shutdown.

### PR DESCRIPTION
**Pull request by bgeltz**
- Fixes #2801.
- Fixes intel-innersource/applications.analyzers.geopm.geopm#51.
- Fixes #2803.

### CODE REVIEW

File: service/src/LevelZero.cpp [hunk 1]
```diff
@@ -15,6 +15,11 @@
 
 #include "LevelZeroImp.hpp"
 
+static void __attribute__((constructor)) geopm_levelzero_init(void)
+{
+    setenv("ZES_ENABLE_SYSMAN", "1", 1);
```
Comment (cmcantalupo) [inline service/src/LevelZero.cpp:20]: this can be within an

```
#ifdef LEVEL_ZERO
```
clause

File: src/Profile.cpp [hunk 2]
```diff
@@ -155,7 +155,7 @@ namespace geopm
             m_is_enabled = true;
         }
         catch (const Exception &ex) {
-            if (m_process < 0) {
+            if (m_process >= 0) {
```
Comment (cmcantalupo) [inline src/Profile.cpp]: m_process is set to a the result of comm_rank() in init_proc_comm() on line 140.  This means that m_process will always be non-negative if we enter the try statement.  I'm not sure why we would condition the warning message based on m_process being positive.

**Review by cmcantalupo — APPROVED** [review]
