### PR TITLE
Fix bug in reporting

### LINKED ISSUE #2863: The controller does not update the reporter every time the ApplicationRecordLog::dump() call is made resulting in lost data
**Describe the bug**
I tried to run with the controller and application starting asynchronously and I expected the report to be correct instead data was missing.

**GEOPM version**
Output from `geopmread --version`
2.0.1

**Expected behavior**
The problem discovered in the ``cloud`` branch exists in the ``dev`` branch as well, but is seen less frequently because the application and controller are started more synchronously.

**Actual behavior**
Time spent by the application was missing from the report, as well as counts for regions.  

**Error messages produced**
Reports could contain negative time for regions, an missing region counts.

**Additional context**
May be related to #2239 but, unclear.

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Always update the reporter object each time the m_application_sampler is updated.
- Failure to do this can result is lost events that are not included in the reporter accounting.
- Fixes #2863

### CODE REVIEW

File: src/Controller.cpp [hunk 1]
```diff
@@ -337,6 +337,7 @@ namespace geopm
         m_platform_io.read_batch();
         m_tracer->update(m_trace_sample);
         m_profile_tracer->update(m_application_sampler.get_records());
+        m_reporter->update();
```
Comment (dannosliwcd) [inline src/Controller.cpp]: One other difference between these header/footer blocks and the `step()`'s `walk_up()` block:

```
        m_tracer->update(m_trace_sample);
        m_profile_tracer->update(m_application_sampler.get_records());
```
are called before `m_reporter->update()` here, but after the reporter inside `walk_up()`. Does that difference matter?

Comment (cmcantalupo) [reply src/Controller.cpp]: It shouldn't matter, but i can make them consistent.

Comment (cmcantalupo) [reply src/Controller.cpp:340]: done!

Comment (cmcantalupo) [reply src/Controller.cpp]: Done now...

**Review by dannosliwcd — APPROVED** [review]
