### PR TITLE
Resolve theta build/run issues

### LINKED ISSUE #1924: Fix for bug #1923
> estimate 0
Fixes #1923, a bug report from github issues.

There were changes in the ``launcher.py`` needed to resolve:
1. The check to ensure that the CPU governor is the same on all the compute nodes in an allocation needs to be updated such that is suppresses the informational job completion message at the end of aprun jobs.
2. Logic that attempts to re-quote quoted arguments before concatenating them needs to be considered for the usage of ``LD_PRELOAD='libgeopm.so'`` when the argv string is constructed.

Additionally, the build syntax in ``tutorial_build_intel.sh`` needs to be able to handle when ``${CC}`` is set to something with a dash argument.

Done criteria:

- [x] Details about the bug are located in the above bug report
- [ ] ~Regression test for the issue was added~
  - Not possible until we setup regular/automatic testing.
- [x] Fix has been verified
- [x] Tutorials compile
- [x] Tutorials run and produce a return code of 0.

### PR DESCRIPTION
**Pull request by bgeltz**
- Fixes #1924, #1923.

### CODE REVIEW

File: integration/config/build.sh [hunk 1]
```diff
@@ -128,7 +128,7 @@ build(){
 
 # Run the service build
 cd service
-CC=gcc CXX=g++ build "${GEOPM_SERVICE_CONFIG_OPTIONS}"
```
Comment (cmcantalupo) [inline integration/config/build.sh:131]: I wonder if we need this change in geopm-service.spec.in?

File: scripts/geopmpy/launcher.py [hunk 2]
```diff
@@ -992,7 +993,7 @@ def launcher_command(self):
         """
         Returns 'srun', the name of the SLURM MPI job launch application.
         """
-        return 'srun'
+        return ['srun']
```
Comment (cmcantalupo) [inline scripts/geopmpy/launcher.py]: It is not very intuitive that a method that is called "launcher_command" should return a list of strings with one element. At the very least, all of the documentation for these methods would have to change to describe the return type as a list, but I'm really not sure why the caller can't be responsible for creating the list that will become argv.  

The way this is resolved for all of the other launcher command line options is to add a new method to the launcher base that returns empty list e.g. quiet_option() and then for the AprunLauncher this would be implemented as return ['-q'].  I'm not saying the launcher class is beautiful, but that is how it works.

**Review by cmcantalupo — CHANGES_REQUESTED** [review]
Thanks for the debug.  I know using Popen without a shell interpreter is pretty confusing, and that is the root cause of the LD_PRELOAD issue.  

I know the launcher is far from perfect, but I'll like to keep the implementation at least consistent.  Please add a new method to the launcher base class.  Thanks!

**Review by cmcantalupo — APPROVED** [review]
