### PR TITLE
Address issues around parallel runs of the integration tests

### LINKED ISSUE #2703: Enhance existing integration test infrastructure to run beta agents
> estimate 1

Done criteria:
- [x] Build with beta
- [x] Build any necessary applications beta tests depend on

### LINKED ISSUE #3014: InitControl object does not handle non-aliased controls
**Describe the bug**
I tried to leverage the InitControl class in an integration test and I expected it to work for non-aliased controls instead they were ignored.

**GEOPM version**
bdabbd83f

**Expected behavior**
Both aliased and non-aliased controls are set properly when leveraging InitControl.

**Actual behavior**
Aliased controls are set properly while non-aliased controls are ignored.

### PR DESCRIPTION
**Pull request by bgeltz**
- Related to #2703.
- Related to #2945.
- Resolves #3014.

### CODE REVIEW

File: service/src/geopm/Helper.hpp [hunk 1]
```diff
@@ -140,6 +140,11 @@ namespace geopm
     /// @param [in] pid The process id to query.
     /// @return The group id.
     unsigned int pid_to_gid(const int pid);
+
+    /// @brief Remove quotes and carriage returns from the profile name.
+    /// @param [in] profile The string to sanatize.
+    /// @return The sanatized string.
+    std::string sanatize_profile(const std::string &profile);
```
Comment (bgeltz) [inline service/src/geopm/Helper.hpp]:
```suggestion
    /// @return The sanitized string.
    std::string sanitize_profile(const std::string &profile);
```

**Review by cmcantalupo — APPROVED** [review]
