### PR TITLE
fixup rollover for powercap and msr drivers

### LINKED ISSUE #3914: Roll over for the RAPL energy counter is not managed for the powercap driver interface
**Describe the bug**
When using the MSR interface to support CPU energy, the implementation handles counter rollover, however the powercap implementation does not.

**GEOPM version**
Output from `geopmread --version`
v3.2.0

**Expected behavior**
The CPU_ENERGY signal should have the same behavior for both driver implementations.

**Actual behavior**
If the msr device driver is used roll over is handled, but for powercap it is not.

**Error messages produced**
None.

**Additional context**
https://github.com/cmcantalupo/kepler/pull/1#discussion_r2160549295

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Fixes #3914
- Also fixes rollover for MSR signals through read_signal interface (reuse RolloverGenerator)

### CODE REVIEW

**Comment by cmcantalupo** [comment]
🤖 

Suggestions

    Consider initializing last_energy on first use to prevent a false overflow:
    C++

    if (overflow_count == 0 && last_energy == 0) {
        last_energy = current_energy;
    }

    Optionally, clarify in comments how thread-local storage is intended to be used.

Summary:
Your rollover logic is sound and should work correctly for unsigned counters. The main thing to double-check is initialization of last_energy to avoid a spurious overflow on the first sample, and to ensure that thread-local storage matches your usage patterns.

Let me know if you want a more detailed code suggestion or review of the surrounding context!

File: libgeopmd/src/CpuinfoIOGroup.cpp [hunk 1]
```diff
@@ -184,11 +184,6 @@ namespace geopm
                             "not valid for CpuinfoIOGroup",
                             GEOPM_ERROR_INVALID, __FILE__, __LINE__);
         }
-        else if (domain_type != GEOPM_DOMAIN_BOARD) {
```
Comment (bgeltz) [inline libgeopmd/src/CpuinfoIOGroup.cpp:187]: Seems the docu already had this set to CPU:
https://geopm.github.io/geopm_pio_cpuinfo.7.html

Since these were previously only allowed to be read at the BOARD level, we should test to make sure the other domains are working as expected re: aggregation.

File: libgeopmd/src/PowercapSysfsDriver.cpp [hunk 2]
```diff
@@ -105,7 +107,18 @@ namespace geopm
         : M_PROPERTIES{SysfsDriver::parse_properties_json(plugin_name(), powercap_sysfs_json())}
         , M_POWERCAP_RESOURCE_BY_NAME(load_powercap_resource_by_name(powercap_directory))
         , M_POWERCAP_DIRECTORY(powercap_directory)
+        , m_rollover_factor(0.0)
     {
+        try {
+            std::string factor_path = POWERCAP_DIRECTORY;
+            factor_path += "/intel-rapl/intel-rapl:0/max_energy_range_uj";
```
Comment (bgeltz) [inline libgeopmd/src/PowercapSysfsDriver.cpp]: Can't you get at this with ``M_PROPERTIES``, ``name_to_property_key()``, and the newly defined ``MAX_ENERGY_RANGE`` instead of duplicating the JSON data here?

File: libgeopmd/src/CpuinfoIOGroup.cpp (hunk 1 above)
Comment (cmcantalupo) [reply libgeopmd/src/CpuinfoIOGroup.cpp:187]: Yeah this check is *actually* the responsibility of PlatformIO.  It only ever makes requests of an IOGroup at the native domain for a signal or control.  These exceptions were both incorrect (board vs CPU) and also redundant.

File: libgeopmd/src/RolloverGenerator.cpp [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+#include <string>
+#include <cmath>
+#include "RolloverGenerator.hpp"
+#include "geopm/Exception.hpp"
+
+namespace geopm
+{
+    RolloverGenerator::RolloverGenerator(int bit_width)
+        : m_last_value(0.0)
+        , m_rollover_factor(pow(2, bit_width))
```
Comment (bgeltz) [inline libgeopmd/src/RolloverGenerator.cpp]: Why set ``m_rollover_factor`` in the initializer list, and also provide the ``set_factor()`` method?  Why both?

File: libgeopmd/src/CpuinfoIOGroup.cpp (hunk 1 above)
Comment (cmcantalupo) [reply libgeopmd/src/CpuinfoIOGroup.cpp:187]: Checked, and LGTM, all the signals are frequencies

File: libgeopmd/src/RolloverGenerator.cpp (hunk 3 above)
Comment (cmcantalupo) [reply libgeopmd/src/RolloverGenerator.cpp]: The constructor takes a bit width, but in the case of powercap, we only get the max value in microjoules.  We could definitly consider having the constructor take the rollover factor directly.

[the remark this answers is not in the document]
Comment (cmcantalupo) [reply libgeopmd/src/RolloverGenerator.cpp]: doesn't work for bit_width == 64, but yet another reason to put get rid of the bit_width constructor.

File: libgeopmd/src/PowercapSysfsDriver.cpp [hunk 4]
```diff
@@ -150,10 +162,18 @@ namespace geopm
                             GEOPM_ERROR_RUNTIME, __FILE__, __LINE__);
         }
         double scaling_factor = prop_it->second.scaling_factor;
-        return [scaling_factor](const std::string &content) {
+        std::shared_ptr<RolloverGenerator> rollover_ptr = nullptr;
+        if (signal_name.find("ENERGY") != std::string::npos) {
+            rollover_ptr = std::make_shared<RolloverGenerator>(64);
+            rollover_ptr->set_factor(m_rollover_factor);
+        }
+        return [scaling_factor, rollover_ptr](const std::string &content) {
```
[the remark this answers is not in the document]
Comment (cmcantalupo) [reply libgeopmd/src/PowercapSysfsDriver.cpp]: we want a copy...rollover_ptr will go out of scope. I'm not sure if we can std::move() in the capture?

File: libgeopmd/src/RolloverGenerator.cpp [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+    {
+        m_rollover_factor = rollover_factor;
+    }
+
+    double RolloverGenerator::update(double value)
+    {
+        if (m_last_value > value) {
+            ++m_num_overflow;
+        }
+        double rollover = m_rollover_factor * m_num_overflow;
```
Comment (bgeltz) [inline libgeopmd/src/RolloverGenerator.cpp]: This could be inside the if statement above as a different member variable to avoid running this calculation during every update() call.

File: libgeopmd/src/PowercapSysfsDriver.hpp [hunk 6]
```diff
@@ -6,11 +6,15 @@
 #ifndef POWERCAPSYSFSDRIVER_HPP_INCLUDE
 #define POWERCAPSYSFSDRIVER_HPP_INCLUDE
 
+#include <memory>
+#include <vector>
```
Comment (bgeltz) [inline libgeopmd/src/PowercapSysfsDriver.hpp]:
```suggestion
#include <memory>
#include <map>
```

File: libgeopmd/test/MSRFieldSignalTest.cpp [hunk 7]
```diff
@@ -143,19 +143,19 @@ TEST_F(MSRFieldSignalTest, read_overflow)
     result = sig->read();
```
Comment (bgeltz) [inline libgeopmd/test/MSRFieldSignalTest.cpp:144]: Comment on 139 should be removed.

File: libgeopmd/test/RolloverGeneratorTest.cpp [hunk 8]
```diff
@@ -0,0 +1,98 @@
+/*
+ * Copyright (c) 2015 - 2025 Intel Corporation
+ * SPDX-License-Identifier: BSD-3-Clause
+ */
+#include <RolloverGenerator.hpp>
+
+
+#include "geopm/SaveControl.hpp"
+
+#include <iostream>
```
Comment (bgeltz) [inline libgeopmd/test/RolloverGeneratorTest.cpp]:
```suggestion
```

File: libgeopmd/test/RolloverGeneratorTest.cpp [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+        int value = idx % 2;
+        EXPECT_EQ(idx, gen.update(value)) << "One bit counter";
+    }
+}
+
+TEST_F(RolloverGeneratorTest, test_two_bit_width)
+{
+    auto gen = RolloverGenerator();
+    gen.set_factor(pow(2, 2));
+    for (int idx = 0; idx < 4; ++idx) {
```
Comment (bgeltz) [inline libgeopmd/test/RolloverGeneratorTest.cpp]:
```suggestion
    for (int idx = 0; idx < 8; ++idx) {
```

File: libgeopmd/test/RolloverGeneratorTest.cpp [hunk 10]
```diff
@@ -0,0 +1,98 @@
...
+
+TEST_F(RolloverGeneratorTest, test_32_bit_width)
+{
+    auto gen = RolloverGenerator();
+    gen.set_factor(pow(2, 32));
+    EXPECT_EQ(1, gen.update(1));
+    double rollover_factor = static_cast<double>(UINT32_MAX) + 1.0;
+    EXPECT_EQ(rollover_factor, gen.update(0));
+    EXPECT_EQ(rollover_factor + 1.0, gen.update(1));
+    EXPECT_NEAR(2.0 * rollover_factor + 1.0, gen.update(0), 1);
```
Comment (bgeltz) [inline libgeopmd/test/RolloverGeneratorTest.cpp]: Could this be EXPECT_EQ?

File: libgeopmd/src/PowercapSysfsDriver.cpp [hunk 11]
```diff
@@ -150,10 +174,18 @@ namespace geopm
                             GEOPM_ERROR_RUNTIME, __FILE__, __LINE__);
         }
         double scaling_factor = prop_it->second.scaling_factor;
-        return [scaling_factor](const std::string &content) {
+        std::shared_ptr<RolloverGenerator> rollover_ptr = nullptr;
+        if (signal_name.find("ENERGY") != std::string::npos) {
+            rollover_ptr = std::make_shared<RolloverGenerator>();
+            rollover_ptr->set_factor(m_rollover_factor);
+        }
+        return [scaling_factor, rollover_ptr = std::move(rollover_ptr)](const std::string &content) {
```
[the remark this answers is not in the document]
Comment (cmcantalupo) [reply libgeopmd/src/PowercapSysfsDriver.cpp:190]: there is one lambda per signal and per domain

File: libgeopmd/test/RolloverGeneratorTest.cpp [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+{
+    auto gen = RolloverGenerator();
+    gen.set_factor(pow(2, 64));
+    double rollover_factor = static_cast<double>(UINT64_MAX) + 1.0;
+    EXPECT_EQ(1, gen.update(1));
+    EXPECT_EQ(rollover_factor, gen.update(0));
+    EXPECT_EQ(rollover_factor + 1.0, gen.update(1));
+    double expected = 2.0 * rollover_factor;
+    // IEEE 754 double precision floating point mantissa bit width is 51
+    double error = 1 << (64 - 51);
```
[the remark this answers is not in the document]
Comment (cmcantalupo) [reply libgeopmd/test/RolloverGeneratorTest.cpp:82]: This is a test....

File: libgeopmd/src/MSRFieldSignal.cpp [hunk 13]
```diff
@@ -75,10 +79,7 @@ namespace geopm
                 result = (1ULL << float_y) * (1.0 + float_z / 4.0);
                 break;
             case MSR::M_FUNCTION_OVERFLOW:
-                if (subfield_last > subfield) {
-                    ++num_overflow;
-                }
-                result = subfield + ((m_subfield_max + 1.0) * num_overflow);
+                result = m_rollover_gen->update(subfield);
```
[the remark this answers is not in the document]
Comment (cmcantalupo) [reply libgeopmd/src/MSRFieldSignal.cpp:82]: Copilot seems to be confused.  There is one MSRFieldSignal per subfield per msr per cpu

File: libgeopmd/src/PowercapSysfsDriver.cpp [hunk 14]
```diff
@@ -105,7 +108,28 @@ namespace geopm
...
+         std::string contents;
+         try {
+             contents = geopm::read_file(factor_path);
+         }
+         catch (const Exception &ex) {
+             throw geopm::Exception("PowercapSysfsDriver: Unable to read RAPL rollover file from sysfs: \"" + factor_path + "\"",
+                                    GEOPM_ERROR_RUNTIME, __FILE__, __LINE__);
+         }
+         try {
+             m_rollover_factor = 1e-6 * std::stoll(contents);
```
Comment (bgeltz) [inline libgeopmd/src/PowercapSysfsDriver.cpp]: A comment explaining where the magic ``1e-6`` came from would be helpful.  Is it possible to put a link to the upstream docu for this sysfs entry here?
Also, should this be a constexpr instead of hard coded here?

**Review by bgeltz — DISMISSED** [review]

File: libgeopmd/src/PowercapSysfsDriver.cpp [hunk 15]
```diff
@@ -105,7 +108,35 @@ namespace geopm
         : M_PROPERTIES{SysfsDriver::parse_properties_json(plugin_name(), powercap_sysfs_json())}
         , M_POWERCAP_RESOURCE_BY_NAME(load_powercap_resource_by_name(powercap_directory))
         , M_POWERCAP_DIRECTORY(powercap_directory)
+        , m_rollover_factor(0.0)
     {
+        std::string signal_name = "POWERCAP::CPU_MAX_ENERGY_RANGE";
+        std::string factor_path = attribute_path(signal_name, 0);
+        std::string property_key = name_to_property_key(signal_name);
```
Comment (bgeltz) [inline libgeopmd/src/PowercapSysfsDriver.cpp:115]:
```suggestion
        std::string property_key = name_to_property_key(signal_name);
        std::string contents;
```

**Review by bgeltz — APPROVED** [review]
