### PR TITLE
In ConstConfigIOGroup, check values against domain size

### LINKED ISSUE #2710: In ConstConfigIOGroup, ensure number of signal values concurs with domain size reported by PlatformTopo
> estimate 1

Currently, ConstConfigIOGroup does not check to ensure the number of signal values concurs with what's actually available for a given domain type. Update the implementation so it performs this check and reports an exception early (when parsing the config file) when such a discrepancy is found.

Done criteria:

- [ ] ~~Integration tests that cover the feature run and pass~~
- [x] Dependencies mocked in unit tests
- [x] Affected unit tests are updated and all tests are passing
- [ ] ~~Documentation changes are not required since this change does
      not modify interfaces or features.~~

### PR DESCRIPTION
**Pull request by avilcheslopez**
- Check the number of values for each signal concurs with domain size reported by PlatformTopo
- Add unit test to validate domain sizes are checked properly

Signed-off-by: Alejandro Vilches <alejandro.vilches@intel.com>

- Fixes #2710

### CODE REVIEW

File: service/src/ConstConfigIOGroup.cpp [hunk 1]
```diff
@@ -330,18 +331,35 @@ namespace geopm
                     properties["aggregation"].string_value());
 
             auto json_values = properties["values"].array_items();
+            if (json_values.empty()) {
+                throw Exception("ConstConfigIOGroup::parse_config_json(): "
+                                "empty array of values provided for " + name,
+                                GEOPM_ERROR_INVALID, __FILE__, __LINE__);
+            }
+            if (static_cast<int>(json_values.size()) != topo.num_domain(domain_type)) {
+                throw Exception("ConstConfigIOGroup::parse_config_json(): "
```
Comment (lhlawson) [inline service/src/ConstConfigIOGroup.cpp:340]: How will this interact with the LevelZero IOGroup if the user hasn't set the ZES_SYSMAN_ENABLE env var or when they change the number of GPUs visible using ZE_AFFFINITY_MASK? 

There could be 18 GPUs in the system and if the user sets ZE_AFINITY_MASK=16 GEOPM will only expose 1 GPU, leading to ConstConfig erroring, even though it may have all the information needed (assuming 18 values are populated).

File: service/test/ConstConfigIOGroupTest.cpp [hunk 2]
```diff
@@ -215,14 +251,18 @@ TEST_F(ConstConfigIOGroupTest, input_empty_domain)
...
         "PlatformTopo::domain_name_to_type(): unrecognized domain_name: "
     );
 }
 
 TEST_F(ConstConfigIOGroupTest, input_empty_description)
 {
+    EXPECT_CALL(*m_default_topo, num_domain(_)).Times(0);
+    EXPECT_CALL(*m_default_topo, num_domain(GEOPM_DOMAIN_GPU))
+        .Times(AtMost(1))
+        .RetiresOnSaturation();
```
Comment (lhlawson) [inline service/test/ConstConfigIOGroupTest.cpp]: This appears to be used by a large number of tests, may be something we can refactor, but it isn't necessarily a high priority.

**Review by lhlawson — APPROVED** [review]
LGTM

**Review by cmcantalupo — APPROVED** [review]
