### PR TITLE
Pin the Controller away from the OS in all cases

### LINKED ISSUE #1594: test_frequency_hint_usage.py - test_frequency_sane_fmap failing intermittently
http://mcfly.ra.intel.com/~test/cron_runs/2021-03-27_0000/test_loop_output.log
```
======================================================================
FAIL: test_frequency_sane_fmap (test_frequency_hint_usage.TestIntegration_frequency_hint_usage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_frequency_hint_usage.py", line 175, in test_frequency_sane_fmap
    msg='Expected achieved frequency to be near default from policy. ({} !~= {})'.format(self._freq_default, achieved_freq))
  File "./util.py", line 297, in assertNear
    self.fail('The fractional difference between {a} and {b} is greater than {epsilon}.  {msg}'.format(a=a, b=b, epsilon=epsilon, msg=msg))
AssertionError: The fractional difference between 2000000000.0 and 1833650000.0 is greater than 0.05.  Expected achieved frequency to be near default from policy. (2000000000.0 !~= 1833650000.0)
 ```

http://mcfly.ra.intel.com/~test/cron_runs/2021-03-28_0000/test_loop_output.log
```
======================================================================
FAIL: test_frequency_sane_fmap (test_frequency_hint_usage.TestIntegration_frequency_hint_usage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_frequency_hint_usage.py", line 175, in test_frequency_sane_fmap
    msg='Expected achieved frequency to be near default from policy. ({} !~= {})'.format(self._freq_default, achieved_freq))
  File "./util.py", line 297, in assertNear
    self.fail('The fractional difference between {a} and {b} is greater than {epsilon}.  {msg}'.format(a=a, b=b, epsilon=epsilon, msg=msg))
AssertionError: The fractional difference between 2000000000.0 and 1842350000.0 is greater than 0.05.  Expected achieved frequency to be near default from policy. (2000000000.0 !~= 1842350000.0)
```

http://mcfly.ra.intel.com/~test/cron_runs/2021-03-29_0000/test_loop_output.log
```
======================================================================
FAIL: test_frequency_sane_fmap (test_frequency_hint_usage.TestIntegration_frequency_hint_usage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_frequency_hint_usage.py", line 175, in test_frequency_sane_fmap
    msg='Expected achieved frequency to be near default from policy. ({} !~= {})'.format(self._freq_default, achieved_freq))
  File "./util.py", line 297, in assertNear
    self.fail('The fractional difference between {a} and {b} is greater than {epsilon}.  {msg}'.format(a=a, b=b, epsilon=epsilon, msg=msg))
AssertionError: The fractional difference between 2000000000.0 and 1859990000.0 is greater than 0.05.  Expected achieved frequency to be near default from policy. (2000000000.0 !~= 1859990000.0)
```

### PR DESCRIPTION
**Pull request by bgeltz**
- If there is an inactive core, run on the highest logical CPU associated with that core.
- If there are no inactive cores, run on the highest logical CPU to keep from having the OS interfere with sampling.
- Resolves #1594, #1598.

### CODE REVIEW

File: src/ApplicationSampler.cpp [hunk 1]
```diff
@@ -407,10 +409,18 @@ namespace geopm
...
                                    "Valid core index returned no nested CPUs");
-                result = *(inactive_cpu.begin());
+                result = *(inactive_cpu.rbegin());
+                found_inactive_core = true;
                 break;
             }
         }
+        if (!found_inactive_core) {
+            // If no inactive cores are found, pin the Controller away from the OS.
+            result = num_cpu - 1;
```
Comment (cmcantalupo) [inline src/ApplicationSampler.cpp]: I think this could just be the initial value assigned at declaration to avoid the extra if condtion.

File: src/ApplicationSampler.cpp [hunk 2]
```diff
@@ -407,10 +409,18 @@ namespace geopm
...
+        }
```
Comment (cmcantalupo) [inline src/ApplicationSampler.cpp:423]: To also stay away from the application this if condition can check for free threads:

```
for (int cpu_idx = m_num_cpu - 1; cpu_idx != -1; --cpu_idx) {
    if (!m_is_cpu_active[cpu_idx]) {
        result = cpu_idx;
        break;
    }
}
```

Comment (cmcantalupo) [reply src/ApplicationSampler.cpp:423]: issue #1598

File: src/ApplicationSampler.cpp [hunk 3]
```diff
@@ -407,10 +409,18 @@ namespace geopm
...
+#ifdef GEOPM_DEBUG
+        std::cout << "Info: <geopm> ApplicationSampler::sampler_cpu(): The Controller will run on logical CPU " << result << std::endl;
```
Comment (cmcantalupo) [inline src/ApplicationSampler.cpp:425]: We will have to be careful about changing this message if PlatformIODaemon owns the ApplicationSampler but is not the Controller thread.  It is not clear to me that we will want to continue to pipe the ApplicationSampler derived signals through PlatformIO at that point...

**Review by cmcantalupo — DISMISSED** [review]
LGTM

**Review by cmcantalupo — DISMISSED** [review]
Good catch

**Review by cmcantalupo — APPROVED** [review]
