### PR TITLE
Makes geopmread/geopmwrite info uniform across IO Groups

### LINKED ISSUE #3025: Incomplete information provided by geopmread/geopmwrite -i option
**Describe the bug**
I tried to use ``geopmwrite`` to query for the information about a control and I expected the output to match the ``geopmread`` output (and overall be consistent) instead incomplete output was observed.

**GEOPM version**
e30c85c64

**Expected behavior**
When inspecting an aliased control with ``geopmwrite``, and an aliased signal with ``geopmread``:
```
$ geopmwrite -i CPU_FREQUENCY_MAX_CONTROL
    description: Target operating frequency of the CPU based on the control register. Note: when querying at a higher domain, if NaN is returned, query at its native domain.
    alias_for: MSR::PERF_CTL:FREQ
    units: hertz
    aggregation: expect_same
    domain: core
    iogroup: MSRIOGroup

$ geopmread -i CPU_FREQUENCY_STATUS
    description: The current operating frequency of the CPU.
    alias_for: MSR::PERF_STATUS:FREQ
    units: hertz
    aggregation: average
    domain: cpu
    iogroup: MSRIOGroup
```

**Actual behavior**
```
$ geopmwrite -i CPU_FREQUENCY_MAX_CONTROL
CPU_FREQUENCY_MAX_CONTROL:
Target operating frequency of the CPU based on the control register.

$ geopmread -i CPU_FREQUENCY_STATUS
CPU_FREQUENCY_STATUS:
    description: The current operating frequency of the CPU.
    iogroup: MSR
    alias_for: MSR::PERF_STATUS:FREQ
```

**Additional context**
Using ``geopmread -i`` with ``CPU_FREQUENCY_MAX_CONTROL`` does give the desired output.
```
$ geopmread -i CPU_FREQUENCY_MAX_CONTROL
CPU_FREQUENCY_MAX_CONTROL:
    description: Target operating frequency of the CPU based on the control register. Note: when querying at a higher domain, if NaN is returned, query at its native domain.
    alias_for: MSR::PERF_CTL:FREQ
    units: hertz
    aggregation: expect_same
    domain: core
    iogroup: MSRIOGroup
```

### PR DESCRIPTION
**Pull request by asmaalrawi**
- Fixes #3025 

* Added units to LevelZeroIOGroup
* Expanded signal/control info string in LevelZeroIOGroup
* Adjusted PlatformIOGroup to get signal descriptions of aliases from original IOGroup

### CODE REVIEW

File: libgeopmd/src/LevelZeroIOGroup.hpp [hunk 1]
```diff
@@ -102,6 +104,7 @@ namespace geopm
                 std::string m_description;
                 std::string m_base_name;
                 std::string m_time_name;
+		int m_units;
```
Comment (bgeltz) [inline libgeopmd/src/LevelZeroIOGroup.hpp]: Please check the indentation here.  It looks off, but that might be GitHub.

File: libgeopmd/src/LevelZeroIOGroup.cpp [hunk 2]
```diff
@@ -1475,7 +1525,17 @@ namespace geopm
                             " not valid for LevelZeroIOGroup.",
                             GEOPM_ERROR_INVALID, __FILE__, __LINE__);
         }
-        return m_signal_available.at(signal_name).m_description;
+
+        signal_info signal = m_signal_available.at(signal_name);
+
+        std::string result;
```
Comment (cmcantalupo) [inline libgeopmd/src/LevelZeroIOGroup.cpp]: Kind of a nit, but would be easier to read if you used a std::ostringstream.

**Review by cmcantalupo — COMMENTED** [review]
Just a nit about using ostringstream

File: libgeopmd/src/NVMLIOGroup.cpp [hunk 3]
```diff
@@ -124,6 +133,7 @@ namespace geopm
                                   "GPU PCIE receive throughput in bytes per second over a 20 millisecond period",
                                   {},
                                   GEOPM_DOMAIN_GPU,
+                                  M_UNITS_HERTZ,
```
Comment (asmaalrawi) [inline libgeopmd/src/NVMLIOGroup.cpp:136]: Hertz isn't really throughput... do we want a new unit for throughput? M_UNITS_BPS ?

**Review by cmcantalupo — DISMISSED** [review]
LGTM

File: docs/source/geopmread.1.rst [hunk 4]
```diff
@@ -158,7 +158,12 @@ Show the description for a signal:
 .. code-block::
 
    $ geopmread --info TIME
-   TIME: Time in seconds since the IOGroup load.
+   TIME:
+       description: Time since the start of application profiling.
+       units: seconds
```
Comment (bgeltz) [inline docs/source/geopmread.1.rst]:
```suggestion
       description: Time since the start of application profiling.
       alias_for: TIME::ELAPSED
       units: seconds
```

File: integration/service/test/test_cli_info.sh [hunk 5]
```diff
@@ -0,0 +1,14 @@
+#!/bin/bash
```
Comment (bgeltz) [inline integration/service/test/test_cli_info.sh:1]: integration/test_geopmio.py was written to capture these sorts of tests.
Why create a new harness and test script instead of integrating into test_geopmio.py?
This new test will not get picked up by the nightly test automation since it is not test_*.py

File: libgeopmd/src/LevelZeroIOGroup.cpp [hunk 6]
```diff
@@ -969,9 +1019,9 @@ namespace geopm
                                                            sleep_time,
                                                            ds.second.m_nan_replace);
                 }
-                m_signal_available[ds.first] = {ds.second.m_description + "\n    alias_for: " +
```
Comment (bgeltz) [inline libgeopmd/src/LevelZeroIOGroup.cpp:972]: Where is "alias_for" injected for this IOGroup?
I see the code for injecting "alias_for" was not modified e.g. in MSRIOGroup.
Is this handled somewhere higher up the stack?
Probably a good thing to add to the test that verifies all signal/control information.

**Review by bgeltz — CHANGES_REQUESTED** [review]
Where is "alias_for"

File: libgeopmd/src/LevelZeroIOGroup.cpp (hunk 6 above)
Comment (asmaalrawi) [reply libgeopmd/src/LevelZeroIOGroup.cpp:972]: The alias_for was injected in two different places for the derivative signals and contained different bits of information. This one set the numerator + rate of change as alias and one further below aliased to the actual IOGroup derivative signal.

Before change:

```
GPU_POWER:
    description: Average GPU power over 40 ms or 8 control loop iterations.  Derivative signal based on LEVELZERO::GPU_ENERGY.
    alias_for: LEVELZERO::GPU_ENERGY rate of change
    alias_for: LEVELZERO::GPU_POWER
    units: watts
    aggregation: sum
    domain: gpu
    iogroup: LevelZeroIOGroup
```

After change:

```
GPU_POWER:
    description: Average GPU power over 40 ms or 8 control loop iterations.  Derivative signal based on LEVELZERO::GPU_ENERGY.
    alias_for: LEVELZERO::GPU_POWER
    units: watts
    aggregation: sum
    domain: gpu
    iogroup: LevelZeroIOGroup
```

File: integration/service/test/test_cli_info.sh (hunk 5 above)
Comment (bgeltz) [reply integration/service/test/test_cli_info.sh:1]: Direction is to move towards using these bash scripts for easier testing and potential documentation that can be shared to users.
Eventually the hope is that all tests in this file will be refactored into bash scripts that are invoked by test_bash_examples.py.
AR: Open an issue to track the refactor of test_geopmio.py into a bash script structure.

File: libgeopmd/src/NVMLIOGroup.cpp (hunk 3 above)
Comment (bgeltz) [reply libgeopmd/src/NVMLIOGroup.cpp:136]: We're going to table this until we can query it programmatically.  Then we'll revisit what the proper units are here.

File: libgeopmd/src/TimeIOGroup.cpp [hunk 7]
```diff
@@ -199,6 +199,9 @@ namespace geopm
 
         std::string result = "Invalid signal description: no description found.";
         result = "    description: Time since the start of application profiling.\n";
+        if (!signal_name.compare("TIME")) {
```
Comment (bgeltz) [inline libgeopmd/src/TimeIOGroup.cpp]:
```suggestion
        if (signal_name == "TIME") {
```

**Review by bgeltz — APPROVED** [review]

**Review by cmcantalupo — APPROVED** [review]
