### PR TITLE
Get rid of geopm_internal.h requirements from base build

### LINKED ISSUE #2237: Build files external to the GEOPM service depend on geopm_internal.h
**Describe the bug**
I tried to build the GEOPM HPC runtime on top of a system installation of the GEOPM service. Several files failed to build due to dependencies on a non-public GEOPM service header, `geopm_internal.h`.

**GEOPM version**
Output from `geopmread --version`: 1.1.0+dev1917g7f9ed5b3

**Expected behavior**
The GEOPM HPC runtime successfully builds by including headers and linking to shared objects from a system installation of the GEOPM service.

**Actual behavior**
The build fails due to missing headers.

**Error messages produced**
Example error (emitted from multiple .cpp and .hpp files):
```
In file included from src/ApplicationSampler.cpp:45:
./src/ProfileSampler.hpp:43:10: fatal error: 'geopm_internal.h' file not found
#include "geopm_internal.h"
         ^~~~~~~~~~~~~~~~~~
```

**Workaround**
Add the service source directory to your include path when configuring your GEOPM HPC runtime build.
```bash
./configure CPPFLAGS="-I$HOME/geopm/service/src"
```

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Need to be able to build the base directory with only
  installed headers.
- Add a header for field operations.
- These functions enable signals to be interpreted as bit fields.
- Relates to #2156
- Fixes #2237

### CODE REVIEW

File: src/geopm_prof.h [hunk 1]
```diff
@@ -40,6 +40,13 @@
 extern "C" {
 #endif
 
+/// @brief Enum for controller launch methods
+enum geopm_ctl_e {
+    GEOPM_CTL_NONE,
+    GEOPM_CTL_PROCESS,
+    GEOPM_CTL_PTHREAD,
+};
```
Comment (avilcheslopez) [inline src/geopm_prof.h]: Not to stop this review, but something to consider maybe for a future change:

Does this enum really belong in geopm_prof.h? After looking at places in the code where it's used, iIt doesn't seem to be related to the profiling functions/functionality.

Alternatively, maybe geopm_prof.h might need to be renamed in the future.

**Review by avilcheslopez — DISMISSED** [review]
Just left a minor note for consideration.

**Review by avilcheslopez — DISMISSED** [review]

**Review by avilcheslopez — DISMISSED** [review]

**Review by bgeltz — DISMISSED** [review]

**Review by bgeltz — APPROVED** [review]
