### PR TITLE
Edit the `trace_signals()` and `report_signals()` in Environment

### LINKED ISSUE #2052: The parser for the GEOPM_REPORT_SIGNALS and GEOPM_TRACE_SIGNALS environment variables do not have proper handling for poorly formatted environment variables or invalid signals
**Describe the bug**
I tried to add a signal to the trace, but I misspelled the name of the signal and I expected a useful error message and a graceful shutdown instead the test in question hangs and the output is the following:

```
2021-12-17 14:45:47.661425

OMP_PROC_BIND=true GEOPM_CTL=process GEOPM_PROFILE=test_epoch_inference GEOPM_AGENT=monitor GEOPM_POLICY=test_epoch_inference-agent-config.json GEOPM_REPORT=test_epoch_inference_no_epoch.report GEOPM_TRACE=test_epoch_inference_trace_no_epoch GEOPM_TRACE_SIGNALS=EPOCH_RUNTIME,EPOCH_RUNTIME_IGNORE,EPOCH_RUNTIME_NETWORK KMP_AFFINITY=disabled MV2_ENABLE_AFFINITY=0 KMP_WARNINGS=FALSE srun -N 1 -n 2 --cpu-bind v,mask_cpu:0x100000000000,0xffffffffffe --export=LD_PRELOAD=libgeopm.so,ALL -I30 -t 100 -J test_epoch_inference -- /home/test-service/geopm-cmcantal/integration/test/.libs/test_epoch_inference --verbose

srun: Loaded msrsave restore plugin.
cpu-bind=MASK - mcfly1, task  0  0 [84662]: mask 0x100000000000 set
cpu-bind=MASK - mcfly1, task  1  1 [84663]: mask 0xffffffffffe set
Error: <geopm> Invalid argument: PlatformIOImp::format_function(): unknown how to format "EPOCH_RUNTIME": at src/PlatformIO.cpp:576
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: All2allModelRegion::All2allModelRegion(): at src/All2allModelRegion.cpp:74
srun: error: mcfly1: task 1: Aborted (core dumped)
```

**GEOPM version**
e8cc00b9e818a7da130df44d16f4ed1c41e8892a

**Expected behavior**
A warning message should be printed and the invalid signal ignored.  Ignoring the entire environment variable would be simple to implement and document, a more subtle implementation would ignore only the signals that are invalid, but allow other use of the mal-formatted environment variable. 

**Actual behavior**
Failure message is a bit unclear, and in some cases a segmentation violation may be happening (see output below).  Additionallly since this failure happens in the middle of the application/controller hand shake, it may also result int stale inter-process shared memory keys and hung applications. 

**Error messages produced**
```
Error: <geopm> Invalid argument: PlatformIOImp::format_function(): unknown how to format "EPOCH_RUNTIME": at src/PlatformIO.cpp:576
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: All2allModelRegion::All2allModelRegion(): at src/All2allModelRegion.cpp:74
srun: error: mcfly1: task 1: Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Krebrov001**
- Modify these methods to use a common internal `signal_parser_method()`
- Modify the Reporter and Tracer classes where these methods are used.
- Move the common code into the `signal_parser_method()`

- Relates to #2052
- Fixes #2052

### CODE REVIEW

File: src/Environment.hpp [hunk 1]
```diff
@@ -40,8 +42,9 @@ namespace geopm
             virtual std::string profile(void) const = 0;
             virtual std::string frequency_map(void) const = 0;
             virtual std::string agent(void) const = 0;
-            virtual std::string trace_signals(void) const = 0;
-            virtual std::string report_signals(void) const = 0;
+            virtual std::vector<std::pair<std::string, int> > trace_signals(void) const = 0;
+            virtual std::vector<std::pair<std::string, int> > report_signals(void) const = 0;
+            virtual std::vector<std::pair<std::string, int> > signal_parser(std::string environment_variable_contents) const = 0;
```
Comment (cmcantalupo) [inline src/Environment.hpp]: signal_parser belongs in EnvironmentImp, not in the public interface of Environment.

File: service/src/geopm/PlatformIO.hpp [hunk 2]
```diff
@@ -248,6 +248,10 @@ namespace geopm
                                             int &server_pid,
                                             std::string &server_key) = 0;
             virtual void stop_batch_server(int server_pid) = 0;
+            /// @brief Query to see if the signal is valid.
+            ///
+            /// @param [in] name Signal to verify.
+            virtual bool signal_exists(const std::string &signal_name) const = 0;
```
Comment (cmcantalupo) [inline service/src/geopm/PlatformIO.hpp]: Although in principle this interface seems useful, we cannot simply append to the PlatformIO C++ interface.  This interface is exposed in C, Python, and through DBus in addition to the C++ implementation.  To add such a public interface to PlatformIO would require wrappers for all these other APIs.  

In addition, the implementation for this method is easily accomplished with an existing PlatformIO interface in all supported languages with something like:

```
    auto signal_names = platform_io().signal_names();
    bool signal_exists = (signal_names.find(signal_name) != signal_names.end());
```

similar code can be used for controls and the `control_names()` method.  I'm not in favor of adding an interface which contains logic that can be easily derived from another interface.

File: src/Environment.cpp [hunk 3]
```diff
@@ -61,12 +65,14 @@ namespace geopm
...
-        : EnvironmentImp(DEFAULT_CONFIG_PATH, OVERRIDE_CONFIG_PATH)
+        : EnvironmentImp(DEFAULT_CONFIG_PATH, OVERRIDE_CONFIG_PATH, nullptr)
     {
 
     }
 
-    EnvironmentImp::EnvironmentImp(const std::string &default_config_path, const std::string &override_config_path)
+    EnvironmentImp::EnvironmentImp(const std::string &default_config_path,
+                                   const std::string &override_config_path,
+                                   const PlatformIO* platform_io)
```
Comment (cmcantalupo) [inline src/Environment.cpp]:
```suggestion
                                   const PlatformIO *platform_io)
```

File: src/Environment.cpp [hunk 4]
```diff
@@ -261,14 +268,47 @@ namespace geopm
...
+        if (m_platform_io == nullptr) {
+            m_platform_io = &PlatformIOProf::platform_io();
+        }
+
+        std::vector<std::pair<std::string, int> > result_data_structure;
+
+        auto individual_signals = geopm::string_split(environment_variable_contents, ",");
+        for (const auto& signal : individual_signals) {
+            auto signal_domain = geopm::string_split(signal, "@");
+            if (!m_platform_io->signal_exists(signal_domain[0])) {
```
Comment (cmcantalupo) [inline src/Environment.cpp]:
```suggestion
        auto signals_avail = m_platform_io->signal_names();
        auto individual_signals = geopm::string_split(environment_variable_contents, ",");
        for (const auto &signal : individual_signals) {
            auto signal_domain = geopm::string_split(signal, "@");
            if (signals_avail.find(signal_domain[0]) == signals_avail.end()) {
```

File: src/Reporter.cpp [hunk 5]
```diff
@@ -419,25 +419,24 @@ namespace geopm
...
-            std::vector<std::string> signal_name_domain = string_split(signal_name, "@");
-            if (signal_name_domain.size() == 2) {
-                int domain_type = m_platform_topo.domain_name_to_type(signal_name_domain[1]);
-                for (int domain_idx = 0; domain_idx < m_platform_topo.num_domain(domain_type); ++domain_idx) {
+        for (const auto& signal_domain_pair : m_env_signals) {
+            if (signal_domain_pair.second == GEOPM_DOMAIN_BOARD) {
+                m_env_signal_name_idx.emplace_back(
+                    signal_domain_pair.first,
+                    m_sample_agg->push_signal(signal_domain_pair.first, GEOPM_DOMAIN_BOARD, 0));
+            } else {
```
Comment (cmcantalupo) [inline src/Reporter.cpp]:
```suggestion
            }
            else {
```

**Review by cmcantalupo — DISMISSED** [review]
Please remove signal_exists() from public PlatformIO interface.  Otherwise looks pretty good.

File: test/EnvironmentTest.cpp [hunk 6]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+
+    m_env = geopm::make_unique<EnvironmentImp>("", "", &m_platform_io);
+
+    expected_signals = {
+        {"CPU_FREQUENCY_MIN", geopm_domain_e::GEOPM_DOMAIN_BOARD},
+        {"CPUINFO::FREQ_STEP", geopm_domain_e::GEOPM_DOMAIN_BOARD},
+        {"TIME", geopm_domain_e::GEOPM_DOMAIN_BOARD}
+    };
+    environment_variable_contents = "CPU_FREQUENCY_MIN,CPUINFO::FREQ_STEP,TIME";
+    actual_signals = ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents);
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
    actual_signals = m_env->signal_parser(environment_variable_contents);
```

File: test/EnvironmentTest.cpp [hunk 7]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+    EXPECT_EQ(expected_signals, actual_signals);
+
+    expected_signals = {
+        {"CPU_FREQUENCY_MIN", geopm_domain_e::GEOPM_DOMAIN_BOARD},
+        {"CPUINFO::FREQ_STEP", geopm_domain_e::GEOPM_DOMAIN_PACKAGE},
+        {"TIME", geopm_domain_e::GEOPM_DOMAIN_CORE}
+    };
+    environment_variable_contents = "CPU_FREQUENCY_MIN,CPUINFO::FREQ_STEP@package,TIME@core";
+    actual_signals = ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents);
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
    actual_signals = m_env->signal_parser(environment_variable_contents);
```

File: test/EnvironmentTest.cpp [hunk 8]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+    EXPECT_EQ(expected_signals, actual_signals);
+
+    expected_signals = {
+        {"CPUINFO::FREQ_STEP", geopm_domain_e::GEOPM_DOMAIN_INVALID},
+        {"TIME", geopm_domain_e::GEOPM_DOMAIN_INVALID}
+    };
+    environment_variable_contents = "CPUINFO::FREQ_STEP@invalid,TIME@invalid";
+    GEOPM_EXPECT_THROW_MESSAGE(
+        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

File: test/EnvironmentTest.cpp [hunk 9]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+        GEOPM_ERROR_INVALID,
+        (std::string("PlatformTopo::domain_name_to_type(): unrecognized domain_name: ") + std::string("invalid"))
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        "PlatformTopo::domain_name_to_type(): unrecognized domain_name: invalid")
```

File: test/EnvironmentTest.cpp [hunk 10]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+    );
+
+    environment_variable_contents = "CPU_FREQUENCY_MIN,CPUINFO::FREQ_STEP@package@core,TIME@core";
+    GEOPM_EXPECT_THROW_MESSAGE(
+        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

File: test/EnvironmentTest.cpp [hunk 11]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+        GEOPM_ERROR_INVALID,
+        (std::string("EnvironmentImp::signal_parser(): Environment trace extension contains signals with multiple \"@\" characters."))
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        "EnvironmentImp::signal_parser(): Environment trace extension contains signals with multiple \"@\" characters.")
```

File: test/EnvironmentTest.cpp [hunk 12]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+    );
+
+    environment_variable_contents = "CPU_FREQUENCY_MIN,NUM_VACUUM_TUBES@package,TIME@core";
+    GEOPM_EXPECT_THROW_MESSAGE(
+        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

File: test/EnvironmentTest.cpp [hunk 13]
```diff
@@ -462,8 +573,60 @@ TEST_F(EnvironmentTest, record_filter_off)
...
+        GEOPM_ERROR_INVALID,
+        (std::string("Invalid signal : ").append("NUM_VACUUM_TUBES"))
```
Comment (bgeltz) [inline test/EnvironmentTest.cpp]:
```suggestion
        "Invalid signal : NUM_VACUUM_TUBES")
```

**Review by bgeltz — CHANGES_REQUESTED** [review]

**Comment by Krebrov001** [comment]
@bgeltz can you please look at this?

**Review by bgeltz — APPROVED** [review]

**Review by cmcantalupo — APPROVED** [review]
