### PR TITLE
Fixed Accelerator chips associating with incorrect CPUs (unrelated to…

### LINKED ISSUE #1955: LevelZero accelerator chips can be associated with the wrong accelerators
**Describe the bug**
I tried to write/read levelzero per chip controls at the board_accelerator level and I expected it to only impact the chips within those physical accelerators.  Instead it impacted multiple chips across several additional accelerators

**GEOPM version**
1.1.0+dev1162g7258c7b1

**Expected behavior**
chips should associate only with accelerators they physically reside on

**Actual behavior**
Chips associate with unrelated accelerators when the number of CPUs on a system aren't cleanly divisible by the number of GPUs AND the number of GPU chips > 1.  

**Error messages produced**
No error messages produced.  Odd frequency setting behavior observed.

### PR DESCRIPTION
**Pull request by lhlawson**
… the chips associated accelerator)

Signed-off-by: lhlawson <lowren.h.lawson@intel.com>

- Fixes #1955 change request from github issues.

Update LevelZero Accelerator topo to guarantee chips only associate with CPUs that their parent accelerator is associated with.

### CODE REVIEW

File: service/src/LevelZeroAcceleratorTopo.cpp [hunk 1]
```diff
@@ -64,54 +64,34 @@ namespace geopm
...
             //       This may come from a call to oneAPI, LevelZero, etc
             for (unsigned int accel_idx = 0; accel_idx <  num_accelerator; ++accel_idx) {
+                int chip_idx = 0;
                 for (unsigned int cpu_idx = accel_idx * num_cpu_per_accelerator;
                      cpu_idx < (accel_idx + 1) * num_cpu_per_accelerator;
                      cpu_idx++) {
                     m_cpu_affinity_ideal.at(accel_idx).insert(cpu_idx);
+
+                    m_cpu_affinity_ideal_chip.at(accel_idx*num_chip_per_accelerator +
+                                                 (chip_idx%num_chip_per_accelerator)).insert(cpu_idx);
```
Comment (bgeltz) [inline service/src/LevelZeroAcceleratorTopo.cpp]:
```suggestion
                    m_cpu_affinity_ideal_chip.at(accel_idx * num_chip_per_accelerator +
                                                 (chip_idx % num_chip_per_accelerator)).insert(cpu_idx);
```

File: service/src/LevelZeroAcceleratorTopo.cpp [hunk 2]
```diff
@@ -64,54 +64,34 @@ namespace geopm
             m_cpu_affinity_ideal.resize(num_accelerator);
             unsigned int num_cpu_per_accelerator = num_cpu / num_accelerator;
 
+            m_cpu_affinity_ideal_chip.resize(num_accelerator_chip);
+            unsigned int num_chip_per_accelerator = num_accelerator_chip / num_accelerator;
+
             // TODO: Add ideal cpu to accelerator affinitization that isn't a simple split if needed.
             //       This may come from a call to oneAPI, LevelZero, etc
```
Comment (bgeltz) [inline service/src/LevelZeroAcceleratorTopo.cpp:71]: Comment to explain this algorithm please.

**Review by bgeltz — CHANGES_REQUESTED** [review]

File: service/test/LevelZeroAcceleratorTopoTest.cpp [hunk 3]
```diff
@@ -233,7 +235,9 @@ TEST_F(LevelZeroAcceleratorTopoTest, high_cpu_count_config)
     std::set<int> cpus_allowed_set_subdevice[num_accelerator_subdevice];
     for (int sub_idx = 0; sub_idx < num_accelerator_subdevice; ++sub_idx) {
         for (int cpu_idx = 0; cpu_idx < num_cpu/num_accelerator_subdevice; ++cpu_idx) {
-            cpus_allowed_set_subdevice[sub_idx].insert(cpu_idx+(sub_idx*4));
+            int accel_idx = sub_idx/(num_accelerator_subdevice/num_accelerator);
+                //cpus_allowed_set_subdevice[sub_idx].insert(cpu_idx+(sub_idx*4));
```
Comment (bgeltz) [inline service/test/LevelZeroAcceleratorTopoTest.cpp]:
```suggestion
```

**Review by bgeltz — CHANGES_REQUESTED** [review]

**Review by bgeltz — APPROVED** [review]
