### PR TITLE
Address issues running geopmctl as root

### LINKED ISSUE #3352: geopmctl fails to run as root
**Describe the bug**
I tried to run geopmctl as root and I expected a useful error message telling me I should not run as a privileged user instead a core dump occurs.

**GEOPM version**
v3.0.1

**Test Setup**
On a compute node where both the service and runtime RPMs have been installed (optional: with the RPM specs modified to configure with ```--enable-debug```), setup a test app as follows:
```
#!/bin/bash
#  Copyright (c) 2015 - 2023, Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
#

TEST_NAME=test_multi_app
export GEOPM_PROFILE=${TEST_NAME}
export GEOPM_PROGRAM_FILTER=sleep,stress-ng
export LD_PRELOAD=libgeopm.so.2.0.0

GEOPM_REPORT=${TEST_NAME}_report.yaml \
GEOPM_TRACE=${TEST_NAME}_trace.csv \
GEOPM_NUM_PROC=2 \
GEOPM_CTL_LOCAL=true \
setsid geopmctl &

# geopmbench
numactl --cpunodebind=0 -- sleep 10 &

# stress-ng
numactl --cpunodebind=1 -- stress-ng --cpu 1 --timeout 10 &

wait $(jobs -p)
```

**Expected behavior**
One of the following:
1. The app runs to completion successfully.
2. The app fails to run, but a useful error message is produced telling me that running the Controller as root is an invalid use case.
3. The app fails to run, and a useful error message is produced telling me why the Controller did not run successfully.

**Actual behavior**
```
mcfly1:~ # ./test_multi_app.sh
stress-ng: info:  [48249] dispatching hogs: 1 cpu
Warning: <geopm> Unable to read MSR configuration from /etc/geopm. Reason: <geopm> Runtime error: Helper::list_directory_files(): failed to open directory '/etc/geopm': No such file or directory: at src/Helper.cpp:155
Warning: <geopm> MSRIOGroup::get_hwp_enabled(): Intel Hardware Performance states are not supported.  Using legacy P-States for signal and control aliases.
Warning: <geopm> Failed to load SST IOGroup.  GEOPM may not work properly unless an alternate IOGroup plugin is loaded to provide signals/controls required by the Controller and Agent.
The error was: <geopm> Bad file descriptor: SSTIOImp::SSTIOImp() failed to get the SST driver version information: at src/SSTIO.cpp:40
Warning: <geopm> Failed to load CNL IOGroup.  GEOPM may not work properly unless an alternate IOGroup plugin is loaded to provide signals/controls required by the Controller and Agent.
The error was: <geopm> No such file or directory: Helper::read_file(): file "/sys/cray/pm_counters/raw_scan_hz" could not be opened: at src/Helper.cpp:44
Warning: <geopm> Failed to load CONST_CONFIG IOGroup.  GEOPM may not work properly unless an alternate IOGroup plugin is loaded to provide signals/controls required by the Controller and Agent.
The error was: <geopm> No such file or directory: Helper::read_file(): file "/etc/geopm/const_config_io.json" could not be opened: at src/Helper.cpp:44
Info: <geopm> Controller will profile PIDs: 48248 48249
Info: <geopm> ApplicationSampler::sampler_cpu(): The Controller will run on logical CPU 87
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: MSRIOImp::adjust(): write_mask is out of bounds: at src/MSRIO.cpp:218
./test_multi_app.sh: line 23: 48247 Aborted                 (core dumped) GEOPM_REPORT=${TEST_NAME}_report.yaml GEOPM_TRACE=${TEST_NAME}_trace.csv GEOPM_NUM_PROC=2 GEOPM_CTL_LOCAL=true setsid geopmctl

stress-ng: info:  [48249] successful run completed in 10.01s
```

**Additional context**
This initial error ```<geopm> Invalid argument: MSRIOImp::adjust(): write_mask is out of bounds: at src/MSRIO.cpp:218``` is misleading as it is *not* the first exception to occur during this failure; it is a side effect.

Upon inspection with GDB, the **real** first exception can be identified.  Single stepping in the debugger shows that the Controller comes up successfully starts into ```Controller::run()```.  The problem occurs in the call to ```m_platform_io.save_control()```.  When attempting to call ```MSRIOGroup::save_control()```, there is an issue in the first ```read_batch()``` call.  The call stack at the time of the error:
```
Breakpoint 3, geopm::MSRIOImp::msr_ioctl (this=0x5555557765a0, batch=...) at src/MSRIO.cpp:273
273             int err = ioctl(msr_batch_desc(), GEOPM_IOC_MSR_BATCH, &batch);
(gdb) bt
#0  geopm::MSRIOImp::msr_ioctl (this=0x5555557765a0, batch=...) at src/MSRIO.cpp:273
#1  0x00007ffff75a9e4c in geopm::MSRIOImp::msr_ioctl_read (this=<optimized out>, ctx=...) at src/MSRIO.cpp:302
#2  0x00007ffff75a9fe0 in geopm::MSRIOImp::read_batch (this=<optimized out>, batch_ctx=<optimized out>) at src/MSRIO.cpp:446
#3  0x00007ffff75acdb4 in geopm::MSRIOGroup::save_control (this=0x555555771b10) at src/MSRIOGroup.cpp:899
#4  0x00007ffff7559f9d in geopm::PlatformIOImp::save_control (this=0x555555770850) at src/PlatformIO.cpp:891
#5  0x00007ffff7b1fe96 in geopm::Controller::run (this=this@entry=0x55555576a140) at src/Controller.cpp:367
#6  0x00007ffff7b200d4 in geopmctl_main (argc=argc@entry=1, argv=argv@entry=0x7fffffffb528) at src/Controller.cpp:89
#7  0x0000555555554bf9 in main (argc=1, argv=0x7fffffffb528) at src/geopmctl_main.cpp:78
```
The result of executing this ```ioctl(...)``` line is ```err = -1```.  Inspecting the errno error message at this point shows: ```Input/output error```.  This ```Input/output error``` is the real error we need to debug in this use case.

Continuing on from this point will result in an exception being thrown out from ```MSRIOImp::msr_ioctl()```.  The exception bubbles all the way up the stack to ```geopmctl_main()``` where it *should* be handled and printed, but the code structure prevents this.  The problematic code in ```geopmctl_main(...)``` are the scoping brackets around the ```ctl``` unique pointer:
https://github.com/geopm/geopm/blob/43fffcb199d4173defc60ac4d72ceec953aac3e1/src/Controller.cpp#L69-L101

Because the exception is generated within the ```ctl->run()``` call, and because this call and the unique pointer to the Controller object are contained within the scoping brackets, the ```catch(...)``` is never hit.  Immediately after the exception occurs and this 4-line block goes out of scope, the ctl object is attempted to be deleted automatically.  However, during this delete, another exception occurs:
```
#0  0x00007ffff6200360 in raise () from /lib64/libc.so.6
#1  0x00007ffff6201941 in abort () from /lib64/libc.so.6
#2  0x00007ffff6b78016 in ?? () from /usr/lib64/libstdc++.so.6
#3  0x00007ffff6b838dc in ?? () from /usr/lib64/libstdc++.so.6
#4  0x00007ffff6b82939 in ?? () from /usr/lib64/libstdc++.so.6
#5  0x00007ffff6b83067 in __gxx_personality_v0 () from /usr/lib64/libstdc++.so.6
#6  0x00007ffff6592eb4 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007ffff6593551 in _Unwind_RaiseException () from /lib64/libgcc_s.so.1
#8  0x00007ffff6b83bdc in __cxa_throw () from /usr/lib64/libstdc++.so.6
#9  0x00007ffff75aa3b9 in geopm::MSRIOImp::adjust (this=<optimized out>, batch_idx=616, raw_value=<optimized out>, write_mask=4, batch_ctx=<optimized out>) at src/MSRIO.cpp:218
#10 0x00007ffff75ab2c8 in geopm::MSRFieldControl::restore (this=<optimized out>) at src/MSRFieldControl.cpp:139
#11 0x00007ffff757622c in geopm::DomainControl::restore (this=<optimized out>) at src/DomainControl.cpp:70
#12 0x00007ffff75acd55 in geopm::MSRIOGroup::restore_control (this=0x555555771b10) at src/MSRIOGroup.cpp:910
#13 0x00007ffff7559d77 in geopm::PlatformIOImp::restore_control (this=0x555555770850) at src/PlatformIO.cpp:904
#14 0x00007ffff7b1bc40 in geopm::Controller::~Controller (this=0x55555576a140, __in_chrg=<optimized out>) at src/Controller.cpp:295
#15 0x00007ffff7b1c097 in geopm::Controller::~Controller (this=0x55555576a140, __in_chrg=<optimized out>) at src/Controller.cpp:296
#16 0x00007ffff7b2013c in std::default_delete<geopm::Controller>::operator() (__ptr=0x55555576a140, this=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:78
#17 std::unique_ptr<geopm::Controller, std::default_delete<geopm::Controller> >::~unique_ptr (this=0x7fffffffb300, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:263
#18 geopmctl_main (argc=argc@entry=1, argv=argv@entry=0x7fffffffb528) at src/Controller.cpp:88
#19 0x0000555555554bf9 in main (argc=1, argv=0x7fffffffb528) at src/geopmctl_main.cpp:78
```

It is this second exception that results in a core dump, and is the cause of the ```<geopm> Invalid argument: MSRIOImp::adjust(): write_mask is out of bounds: at src/MSRIO.cpp:218``` message that is shown in the shell.

**GDB setup**
In addition to installing all RPMs built with ```--enable-debug``` at configure time, the following changes were made to the repro script above:
1. Comment out the lines that setup/call ```geopmctl```.  You will be running this manually.
2. Setup 2 terminal windows on the same compute node, logged in as root.
3. In window 1 issue: ```GEOPM_REPORT=report.yaml GEOPM_TRACE=trace.csv GEOPM_NUM_PROC=2 GEOPM_CTL_LOCAL=true gdb-oneapi /usr/bin/geopmctl```.  Let it run for a moment, then interrupt it with ctrl-c, issue ```break MSRIO.cpp:273```, and then continue.
4. In window 2 issue: ```./test_multi_app.sh```.
5. Step through ```msr_ioctl()``` in window 1 to observe the errors.

### PR DESCRIPTION
**Pull request by bgeltz**
- Fixes #3352.

### CODE REVIEW

File: src/Controller.cpp [hunk 1]
```diff
@@ -261,6 +261,10 @@ namespace geopm
         , m_do_init_control(do_init_control)
         , m_do_restore(false)
     {
+        if (geopm::has_cap_sys_admin()) {
+            throw Exception("Controller cannot be run as root",
```
Comment (cmcantalupo) [inline src/Controller.cpp]:
```suggestion
            throw Exception("Controller cannot be run with CAP_SYS_ADMIN",
```

**Review by cmcantalupo — DISMISSED** [review]

File: service/src/MSRFieldControl.cpp [hunk 2]
```diff
@@ -47,9 +51,13 @@ namespace geopm
             throw Exception("MSRFieldControl: begin bit must be <= end bit",
                             GEOPM_ERROR_INVALID, __FILE__, __LINE__);
         }
-
-        m_save_idx = m_msrio->add_read(m_cpu, m_offset, m_save_restore_ctx);
-        m_restore_idx = m_msrio->add_write(m_cpu, m_offset, m_save_restore_ctx);
+        uint64_t offset_mask = m_msrio->system_write_mask(m_offset);
```
Comment (bgeltz) [inline service/src/MSRFieldControl.cpp:54]: Add LUT to system_write_mask() to avoid repeatedly calling it after we've done 1 lookup.  The mask won't change.

File: service/src/MSRIOGroup.cpp [hunk 3]
```diff
@@ -1717,6 +1740,19 @@ namespace geopm
...
+        bool is_trl_writable = false;
+        try {
+            is_trl_writable = is_trl_writable_in_all_domains(root["msrs"], platform_topo(), MSRIO::make_unique(MSRIO::M_DRIVER_MSRSAFE));
+        }
+        catch (const Exception &ex) {
+            std::cerr << "warning: <geopm> msriogroup::" << std::string(__func__)
+                      << "(): unable to check trl via platform_info: "
+                      << ex.what() << std::endl
+                      << "put this initial allowlist in place and rerun to allow for "
+                      << "platform_info inspection." << std::endl;
```
Comment (bgeltz) [inline service/src/MSRIOGroup.cpp]:
```suggestion
                      << "PLATFORM_INFO inspection." << std::endl;
```

Comment (bgeltz) [reply service/src/MSRIOGroup.cpp]: Change this around so that the TRL check uses the stock MSR driver initially to do the PLATFORM_INFO inspection.
Temporarily modprobe msr, run the check, then rmmod msr, even if msr-safe is present.

File: src/Controller.cpp [hunk 4]
```diff
@@ -261,6 +261,10 @@ namespace geopm
         , m_do_init_control(do_init_control)
         , m_do_restore(false)
     {
+        if (geopm::has_cap_sys_admin()) {
+            throw Exception("Controller cannot be run with CAP_SYS_ADMIN.  Try again as a "
+                            "non-root user.", GEOPM_ERROR_RUNTIME, __FILE__, __LINE__);
+        }
```
Comment (bgeltz) [inline src/Controller.cpp]: Remove as running the Controller as root works now.

File: service/src/MSRFieldControl.cpp (hunk 2 above)
Comment (bgeltz) [reply service/src/MSRFieldControl.cpp:54]: This already exists in the system_write_mask() implementation.

File: service/geopmdpy/access.py [hunk 5]
```diff
@@ -301,8 +309,26 @@ def read_names(self, fid):
...
+
+        Generates the minimal msr-safe allowlist required for
+        GEOPM to access all the expected signals and controls.
+
+        Returns:
+            str: msr-safe allowlist string.
+
+        """
+        global _dl
+        name_max = 4096
```
Comment (bgeltz) [inline service/geopmdpy/access.py]:
```suggestion
        data_max = 2MB
```

File: service/geopmdpy/access.py [hunk 6]
```diff
@@ -388,11 +417,14 @@ def run(self, is_write, is_all, is_control, group, is_default, is_delete,
...
                 else:
                     output = self.get_group_signals(group)
+            elif is_msr_safe:
+                output = self.get_msr_safe_allowlist()
             else:
                 if is_control:
                     output = self.get_user_controls()
                 else:
                     output = self.get_user_signals()
+
```
Comment (bgeltz) [inline service/geopmdpy/access.py]:
```suggestion
```

File: service/docs/source/geopmaccess.1.rst [hunk 7]
```diff
@@ -349,6 +347,50 @@ and combine access lists when writing to a shared mount point.
...
+Without the allowlist, msr-safe will not provide access to MSRs even
+for privileged users.  For more information see: :ref:`requires:The MSR
+Driver`.
+
+The following example demonstrates the necessary commands to set the
+msr-safe allowlist using ``geopmaccess``:
+
+.. code-block:: bash
+
+    # Run the following with root or sudo:
```
Comment (bgeltz) [inline service/docs/source/geopmaccess.1.rst:368]: If msr is already loaded, avoid modprobe msr and rmmod.  Check if there's an RC with modprobe that can be examined.

Comment (bgeltz) [reply service/docs/source/geopmaccess.1.rst:368]: modprobe has a 0 RC even if the module is already loaded 😮

**Review by cmcantalupo — APPROVED** [review]
