### PR TITLE
Fix issue with save/restore and writing in general

### LINKED ISSUE #3311: CpufreqIOGroup breaks the integration tests when doing save/restore
**Describe the bug**
I tried to run the nightlies and they failed with errors about writing to cpufreq sysfs files

**GEOPM version**
Output from `geopmread --version`
https://github.com/geopm/geopm/commit/2f17aa2a0989aa3382fd5831ee5617587edd55f7

**Expected behavior**
Writing should be enabled.

**Actual behavior**
Cannot write to any controls.

**Error messages produced**
```
cmcantal@mcfly1:~/Git/geopm/service (dev)]$ geopmwrite CPUFREQ::SCALING_MAX_FREQ cpu 0 2.1e9
Error: cannot write control: <geopm> Invalid argument: PlatformIOImp::write_control(): unable to write control name "CPUFREQ::SCALING_MAX_FREQ" and domain type "3"
The following errors were observed:
<geopm> Runtime error: SDBus: Failed to call sd-bus function sd_bus_call_method(), error:-5 name: not.known.Error.RuntimeError: geopm_pio_write_control() failed: <geopm> Invalid argument: PlatformIOImp::write_control(): unable to write control name "CPUFREQ::SCALING_MAX_FREQ" and domain type "3"
The following errors were observed:
<geopm> Invalid argument: SysfsIOGroup failed to write control: at src/SysfsIOGroup.cpp:82
: at src/PlatformIO.cpp:859: at src/SDBus.cpp:32
: at src/PlatformIO.cpp:859
```

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Fixes #3311

### CODE REVIEW

**Review by dannosliwcd — DISMISSED** [review]

**Review by dannosliwcd — DISMISSED** [review]

File: service/src/SaveControl.cpp [hunk 1]
```diff
@@ -131,10 +133,12 @@ namespace geopm
     void SaveControlImp::restore(IOGroup &io_group) const
     {
         for (const auto &ss : settings()) {
-            io_group.write_control(ss.name,
-                                   ss.domain_type,
-                                   ss.domain_idx,
-                                   ss.setting);
+            if (std::isfinite(ss.setting)) {
```
Comment (bgeltz) [inline service/src/SaveControl.cpp:136]: Why are we trying to restore NaNs?  That seems like the "real" bug.

File: service/src/SaveControl.cpp [hunk 2]
```diff
@@ -131,10 +133,12 @@ namespace geopm
...
+                io_group.write_control(ss.name,
+                                       ss.domain_type,
+                                       ss.domain_idx,
+                                       ss.setting);
+            }
```
Comment (bgeltz) [inline service/src/SaveControl.cpp:141]: else emit warning to all the proper spots

**Review by bgeltz — CHANGES_REQUESTED** [review]

File: service/src/SysfsIOGroup.cpp [hunk 3]
```diff
@@ -559,6 +557,10 @@ namespace geopm
             throw Exception("SysfsIOGroup::" + method_name + "(): domain_idx out of range.",
                             GEOPM_ERROR_INVALID, __FILE__, __LINE__);
         }
+        if (control_name != "" && m_unsaved_controls.count(cname) != 0) {
+            throw Exception("SysfsIOroup::" + method_name + "(): Cannot write control setting which could not be read.",
```
Comment (bgeltz) [inline service/src/SysfsIOGroup.cpp]:
```suggestion
            throw Exception("SysfsIOGroup::" + method_name + "(): Cannot write control setting which could not be read.",
```

**Review by bgeltz — DISMISSED** [review]

**Review by bgeltz — APPROVED** [review]
