### PR TITLE
Fix issue with ACNT and MCNT msr aggregation

### LINKED ISSUE #1737: ACNT, MCNT and PCNT aggregation in report files is broken
When ACNT, MCNT and PCNT are dumped in report files at both core level and package level, the package level values seem to be picking up the first value instead of sum or averages of values in a package.

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Aggregation method was not specified in json description.
- Default is "select_first", which is not correct in this case.
- Set aggration to sum which is the type for all counters.
- Fixes #1737 from github issues.

### CODE REVIEW

File: src/msr_data_arch.cpp [hunk 1]
```diff
@@ -69,6 +69,7 @@ namespace geopm
                     "scalar":    1.0,
                     "behavior":  "monotone",
                     "writeable": false
+                    "aggregation": "sum"
```
Comment (fkeceli) [inline src/msr_data_arch.cpp:72]: Is this missing a comma at the previous line?

File: src/msr_data_arch.cpp [hunk 2]
```diff
@@ -84,6 +85,7 @@ namespace geopm
...
```
Comment (fkeceli) [inline src/msr_data_arch.cpp:88]: Is this missing a comma at the previous line?

**Review by fkeceli — APPROVED** [review]
