### PR TITLE
Fix for monotone frequency test

### LINKED ISSUE #848: Intermittent failures of test_monotone_frequency
Nightly tests fail occasionally with the following result:

```
======================================================================
FAIL: test_monotone_frequency (test_integration.test_ee_stream_dgemm_mix.TestIntegrationEEStreamDGEMMMix)
Test that agent selects lower frequencies for regions with more
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/geopm/test_integration/test_ee_stream_dgemm_mix.py", line 158, in test_monotone_frequency
    msg='Chosen frequency decreased with increasing dgemm fraction')
AssertionError: Chosen frequency decreased with increasing dgemm fraction
```

### PR DESCRIPTION
**Pull request by dianarg**
- Change spin region to ignore hint
- Change to use timed and scaling regions.
- Fixes #848

### CODE REVIEW

**Comment by dianarg** [comment]
Saw 50 passes with the scale factor set to 1 sec.  I've reduced it to 0.5 to retest to see if we can make this test run faster.

Update: 0.5 seconds seems too short; saw some failures.

File: test_integration/test_ee_timed_scaling_mix.cpp [hunk 1]
```diff
@@ -59,54 +59,59 @@ int main(int argc, char **argv)
...
-        int dgemm_idx = mix_idx;
-        double stream_big_o = stream_factor * mix_factor * stream_idx;
-        double dgemm_big_o = dgemm_factor * mix_factor * dgemm_idx;
-        std::unique_ptr<geopm::ModelRegion> stream_model(geopm::ModelRegion::model_region("stream-unmarked", stream_big_o, is_verbose));
-        std::unique_ptr<geopm::ModelRegion> dgemm_model(geopm::ModelRegion::model_region("dgemm-unmarked", dgemm_big_o, is_verbose));
+        int timed_idx = num_mix - 1 - mix_idx;
+        int scaling_idx = mix_idx;
+        double timed_big_o = timed_factor * mix_factor * timed_idx;
+        double scaling_big_o = scaling_factor * mix_factor * scaling_idx;
+        std::unique_ptr<geopm::ModelRegion> timed_model(geopm::ModelRegion::model_region("timed_scaling-unmarked", timed_big_o, is_verbose));
```
Comment (cmcantalupo) [inline test_integration/test_ee_timed_scaling_mix.cpp:80]: The scaling model region object constructors should be wrapped in the ignore hint.

**Review by cmcantalupo — COMMENTED** [review]
Just the issue we discussed about not calibrating for the model region

**Review by cmcantalupo — APPROVED** [review]
