### PR TITLE
Reset nvml after fork

### LINKED ISSUE #3066: Batch server fails when requesting GPU_ENERGY from the NVMLIOgroup
**Describe the bug**
I tried to use geopmsession to read GPU_ENERGY on a system with NVIDIA GPUs and it failed with an uninitialized error from NVML.  This is likely due to the fork(2) call after libnvml is initialized.  Note that serial access with geopmread functions correctly.

**GEOPM version**
df0713c

**Expected behavior**
Expected batch access to work through the GEOPM Service for NVML signals

**Actual behavior**
Batch server fails to call into NVML library after fork(2).

**Error messages produced**
```
Aug 16 16:07:20 saruman geopmd[2705866]: Warning: <geopm>: src/BatchServer.cpp:416 Batch server was terminated with exception: <geopm> Invalid argument: PlatformIOImp::push_signal(): no support for signal name "GPU_ENERGY" and domain type "8"
Aug 16 16:07:20 saruman geopmd[2705866]: The following errors were observed:
Aug 16 16:07:20 saruman geopmd[2705866]: <geopm> Runtime error: NVMLDevicePool::energy: NVML failed to get energy for GPU 0. : Uninitialized: at src/NVMLDevicePool.cpp:238
```

### PR DESCRIPTION
**Pull request by cmcantalupo**
- Add -j option to make in debian rules
- Fixes #3066

### CODE REVIEW

File: service/src/BatchServer.cpp [hunk 1]
```diff
@@ -23,12 +24,14 @@
...
 #include "POSIXSignal.hpp"
 #include "geopm_debug.hpp"
+#include "NVMLDevicePool.hpp"
 
 volatile static sig_atomic_t g_sigterm_count = 0;
 volatile static sig_atomic_t g_sigchld_count = 0;
 volatile static sig_atomic_t g_sigchld_status = 0;
 volatile static sig_atomic_t g_wait_status = 0;
 
+
```
Comment (bgeltz) [inline service/src/BatchServer.cpp]:
```suggestion
```

File: service/src/BatchServer.cpp [hunk 2]
```diff
@@ -83,6 +86,10 @@ namespace geopm
     {
         // Fork the server when calling real constructor.
         auto setup = [this]() {
+            // NVML requires reinitialization after fork
+            // TODO: Switch to fork()/excecv() model to
+            //       avoid this issue
+            nvml_device_pool(geopm_sched_num_cpu()).reset();
```
Comment (bgeltz) [inline service/src/BatchServer.cpp:94]: ```#ifdefs``` for non-NVML systems?

**Review by bgeltz — CHANGES_REQUESTED** [review]

**Review by bgeltz — DISMISSED** [review]

**Review by bgeltz — APPROVED** [review]
